### ISSUE TITLE
Launcher icon causes build errors

### ISSUE THREAD

**Issue by psyren89** [feedhenry/fh-android-sdk#36]
Going by the instructions in the readme, on compiling a project with Gradle, this error is produced.

```
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:6:18-52
    is also present at [com.feedhenry:fh-android-sdk:2.3.1] AndroidManifest.xml:14:18-54 value=(@drawable/ic_launcher)
    Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:4:5-9:19 to override
```

I would suggest removing the app icon from the library as well as the manifest's `<application>` tag.

**Comment by danielpassos** [comment]
There is no icon on library anymore: https://github.com/feedhenry/fh-android-sdk/blob/master/library/src/main/AndroidManifest.xml
