### ISSUE TITLE
Version does not update correctly

### ISSUE THREAD

**Issue by psyren89** [feedhenry/fh-android-sdk#37]
In `FH.java`, on line 55, there is a field indicating the SDK version with the comment `// DO NOT CHANGE, the ant build task will automatically update this value. Update it in VERSION.txt`.

A search of the repo indicates there is no `VERSION.txt`. As of release 2.3.1, `FH.VERSION` still returns `2.1.0`.

**Comment by danielpassos** [comment]
@psyren89 Is this still valid?

**Comment by psyren89** [comment]
No idea, I haven't touched this since opening this issue. Close this if you wish.

**Comment by danielpassos** [comment]
@psyren89 Sorry for the long time to look into it.
