### ISSUE TITLE
JSON git submodule?

### ISSUE THREAD

**Issue by psyren89** [feedhenry/fh-android-sdk#43]
Currently, the JSON library bundled with the SDK is a direct copy of code from [the source](https://github.com/douglascrockford/JSON-java). Would it be reasonable to make it a git submodule so that keeping it up to date is simpler?

The last release on the Maven Central Repo is dated at the end of last year (20141113).

**Comment by psyren89** [comment]
After a brief attempt, it seems we can't use the latest code without some changes to the compilation process - namely, bumping the minimum Java SDK version to 1.7.

**Comment by wei-lee** [comment]
@psyren89 we are not using the latest version of the source, we are using an old version of it. The reason is that when the JSON object is serialized, we need to make sure the keys are sorted alphabetically to keep the hash value consistent across different devices for the sync framework.

**Comment by danielpassos** [comment]
@psyren89 I tried do something similar but it's not so easy.

**Comment by psyren89** [comment]
If that's the case, I'll port over what improvements I can and do some optimisations on what's there.

**Comment by psyren89** [comment]
Which classes did you modify from the original?

**Comment by wei-lee** [comment]
@psyren89 this line here: https://github.com/feedhenry/fh-android-sdk/blob/master/fh-android-sdk/src/main/java/org/json/fh/JSONObject.java#L520.

**Comment by psyren89** [comment]
How about https://github.com/feedhenry/fh-android-sdk/blob/master/fh-android-sdk/src/main/java/org/json/fh/JSONObject.java#L312 ?

**Comment by wei-lee** [comment]
@psyren89 yeah, and that too.

**Comment by psyren89** [comment]
Consider the following:
***Pros:***
* Keep up to date with the master branch of the library without having to manually port code over.
* No modification of the library files (as seen above) - simply write a class that `extends JSONObject` (or even a utility class) with only the desired methods (`append()` and `sortedKeys()`).
* Code maintenance is taken out of our hands.

***Cons:***
* Package references (`org.json.fh`) need to be updated (to just `org.json`).
* No possibility of our own improvements/optimisations to the library unless we make PRs against their repo, which could take some time.
* Initial testing showed that Maven's Javadoc plugin did not like the library - I had trouble trying to get it to ignore the package.
* Code maintenance is taken out of our hands.

***Things to bear in mind:***
* The library was "recently" updated to support Java 8. At the present time, there are no Java 8 specific features used, but if they ever do appear, this may cause issues as Android does not support this language level. However, if this is the case, we can freeze the submodule at at particular commit, which would be the case were we to manually maintain the library in the repo.

With this in mind, how do you feel about using a submodule?
