### ISSUE TITLE
Minimum Java version -> 1.7?

### ISSUE THREAD

**Issue by psyren89** [feedhenry/fh-android-sdk#44]
Should we consider bumping the minimum compile SDK to Java 7? Consider that Android received "official support" for Java 7 in 2013, with all features except try-with-resources available to API18 and below.
This would allow us to bring the JSON library in as a submodule (although documentation testing is still an issue).

https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/user-guide#TOC-Using-sourceCompatibility-1.7

**Comment by wei-lee** [comment]
+1

**Comment by danielpassos** [comment]
+1 to Java 7
-1 to submodule

**Comment by psyren89** [comment]
Implemented in commit 8c62f281d4605f20bf37acbd5d7aa90a0a6f9e8b.
