### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by johnhiott** [feedhenry/fh-android-sdk#48]
On slow calls, I always get a timeout.  These calls typically return in 8-10 seconds on the iOS client.  However, in Android, they timeout.  I need to be able to change the timeout value in the Android client.
I cannot have checked the documentation and source.

**Comment by secondsun** [comment]
Does this : https://github.com/feedhenry/fh-android-sdk/commit/2f25f638b950d05a60716d7745c3361a2926202e resolve your issue?
